Remove all LiveData and LiveEvent and replace with StateFlow and SharedFlow
BottleRocketStudios/Android-ArchitectureDemo pull request #23
Opened 2021-10-21 22:52 UTC by IvanTelisman

2021-10-21 22:54 UTC, IvanTelisman commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/auth/LoginViewModel.kt
> +    val loginEnabled: StateFlow<Boolean> = combine(email, password) { (email, password) ->
Nice thanks for this example, I was just looking into how to utilize this combine function

2021-10-22 17:14 UTC, jaredstockton reviewed
@IvanTelisman Added some comments on reasons for some of the changes in my review commits. Once you feel like you've completed the changes from LiveData/LiveEvent to StateFlow/SharedFlow, please update this PR from being a draft to being a normal PR and I'll take another look 😃

2021-10-22 17:14 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/auth/LoginViewModel.kt
> +    val loginEnabled: StateFlow<Boolean> = combine(email, password) { (email, password) ->
This is one of the benefits of using Flow over LiveData. IMO it is less code and more readable

2021-10-22 17:14 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/devoptions/DevOptionsFragment.kt
> +        viewLifecycleOwner.lifecycleScope.launch {
@IvanTelisman  I changed from using `lifecycleScope.launchWhenStarted` to `viewLifecycleOwner.lifecycleScope.launch` for two reasons:

1. We should be using the `viewLifecycleOwner.lifecycleScope` so that the collection will be stopped/canceled when the fragment's view is destroyed. Using just `lifecycleScope` will use the actual fragment's lifecycle, which can be longer than the fragment's view lifecycle. Attempting to update UI when the fragment's view is destroyed will result in crashes.
2. Since we are calling this inside setupBinding (which is called in onViewCreated), I don't see any benefit to using `.launchWhenStarted` over `.launch`.
Additionally, [Google's api docs](https://developer.android.com/topic/libraries/architecture/coroutines#lifecyclescope) as well as [medium blog posts](https://medium.com/androiddevelopers/a-safer-way-to-collect-flows-from-android-uis-23080b1f8bda) (with link to [this gist](https://gist.github.com/manuelvicnt/a26e26179b80d8a278c634cc5f7a9a78#file-repeatonlifecyclefragment-kt)) showcase this style of usage within a fragment's `onViewCreated` function.

2021-10-22 17:14 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/devoptions/DevOptionsViewModel.kt
> +    sealed class DevOptionsEvent {
@IvanTelisman Nice addition to funnel all events through a common Flow!

2021-10-24 20:54 UTC, IvanTelisman commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/MainActivityViewModel.kt
> +    val avatarUrl = repo.user.map { it?.avatarUrl.orEmpty() }.stateIn(viewModelScope, SharingStarted.Lazily, "")
Just saw that I can consolidate this utilizing that groundState extension function, I'll get that updated

2021-10-25 14:12 UTC, jaredstockton requested changes
@IvanTelisman Left some feedback on changes made

2021-10-25 14:12 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/MainActivityViewModel.kt
> +    fun showToolbar(show: Boolean) = showToolbar.setNullable(show)
@IvanTelisman Use `.set` instead of `.setNullable` here

2021-10-25 14:12 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryFolderFragmentViewModel.kt
> +        viewModelScope.launch {
@IvanTelisman Use `viewModelScope.launch(dispatcherProvier.IO)` here (injecting the DispatcherProvider via constructor injection and modifying the `DataModule`)

2021-10-25 14:12 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryFolderFragmentViewModel.kt
> +    val srcFiles: StateFlow<List<RepoFile>?> = MutableStateFlow(emptyList())
@IvanTelisman Let's specify/use a non-nullable List here and use the empty list instead as there is no need to have any knowledge of null vs empty.

2021-10-25 14:12 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryFolderFragmentViewModel.kt
> +                    srcFiles.setNullable(result.data)
@IvanTelisman Use `.set` instead of `.setNullable` here

2021-10-25 14:12 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryFolderFragmentViewModel.kt
> +                }
@IvanTelisman Simplify logic here since files will be non-null once other comments are addressed

2021-10-25 14:12 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryFragmentViewModel.kt
> +        viewModelScope.launch {
@IvanTelisman Use `viewModelScope.launch(dispatcherProvier.IO)` here

2021-10-25 14:12 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryFragmentViewModel.kt
> +    val srcFiles: StateFlow<List<RepoFile>?> = MutableStateFlow(emptyList())
@IvanTelisman Let's specify/use a non-nullable List here and use the empty list instead as there is no need to have any knowledge of null vs empty.

2021-10-25 14:12 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryFragmentViewModel.kt
> +    val selectedRepository: StateFlow<Repository?> = MutableStateFlow(Repository())
@IvanTelisman Use `MutableStateFlow(null)` here rather than creating an empty Repository via `MutableStateFlow(Repository())`

2021-10-25 14:12 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/snippet/CreateSnippetFragmentViewModel.kt
> +    // Two way databinding
@IvanTelisman Thanks for the section delineation here!

2021-10-25 14:12 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/snippet/CreateSnippetFragmentViewModel.kt
> +                contents.value.let { contentsString ->
@IvanTelisman The `.let` is not needed here since the values are now non-null. Go ahead and remove them to simplify the code

2021-10-25 14:12 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryFragmentViewModel.kt
> +                            is ApiResult.Success -> srcFiles.setNullable(result.data)
@IvanTelisman Use `.set` instead of `.setNullable` as srcFiles should be non-null after other comments are addressed

2021-10-25 14:57 UTC, IvanTelisman commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryFragmentViewModel.kt
> +        viewModelScope.launch {
Hey @br-jared-stockton, I had initially tried that but was getting a CalledFromWrongThreadException crash with it there.

2021-10-25 14:58 UTC, IvanTelisman commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryFragmentViewModel.kt
> +    val selectedRepository: StateFlow<Repository?> = MutableStateFlow(Repository())
That makes sense, I'll get this cleaned up.

2021-10-25 15:00 UTC, IvanTelisman commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/snippet/CreateSnippetFragmentViewModel.kt
> +                contents.value.let { contentsString ->
@br-jared-stockton, sounds good I'll get all of this unneeded null safety code outa there. Thanks!

2021-10-25 15:13 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryFragmentViewModel.kt
> +        viewModelScope.launch {
@IvanTelisman Thanks for mentioning that! Since Section here is a Groupie type (related to UI - probably shouldn't live here in the codebase but that can be tackled later on), it is likely modifying some UI which is causing the crash since UI must be modified on the main thread. To switch to the main thread, you can use `withContext` as seen below to switch the context for certain blocks of code:

```
...
val map = files?.map { RepoFileViewModel(it) }
withContext(dispatcherProvider.Main) {
    map?.let {
        filesGroup.setHeader(FolderHeaderViewModel(selectedRepository.value?.name ?: "", it.size))
        filesGroup.update(map)
    }
}
...
```

2021-10-25 17:58 UTC, IvanTelisman commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryFragmentViewModel.kt
> +        viewModelScope.launch {
That makes sense, I'll add explicitly setting which thread. Thanks!

2021-10-25 23:06 UTC, IvanTelisman commented
@br-jared-stockton Updated the PR to reflect those latest changes per the PR feedback and just a heads-up that Ulises work for the "Define Arrange act assert testing pattern in codebase" task was included in this PR as well since he was needing the changes from the adding Turbine update.

2021-10-25 23:14 UTC, IvanTelisman commented on app/src/test/java/com/bottlerocketstudios/brarchitecture/ui/BaseBindableViewModelTest.kt
> +    fun baseBindableViewModel_shouldBeInstanceOf_ViewModelItem(){
Hey @UlisesXumak looks like there are a couple places where you will want to fix your "camelCase" usage with these function names

2021-10-27 20:05 UTC, jaredstockton approved these changes
@IvanTelisman @AmaoApps Changes look good! Made a few tweaks in a review commit but this should be ready to merge now 😄

2021-10-27 20:10 UTC, merged