Top App bar, back nav, web view nav
BottleRocketStudios/Android-ArchitectureDemo pull request #59
Opened 2022-04-07 14:35 UTC by BottleRocket-Colin

Initial pass at top app bar and navigation integration

2022-04-07 14:39 UTC, BottleRocket-Colin commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/MainNavGraph.kt
> +        // return
Going to add this in as part of next PR.

2022-04-07 14:41 UTC, BottleRocket-Colin commented on compose/src/main/java/com/bottlerocketstudios/compose/auth/AuthCode.kt
> +    WebView(
Converted from Android view wrapper to accompanist web view.

2022-04-07 14:51 UTC, BottleRocket-Colin commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/ComposeActivity.kt
> +                            visible = activityViewModel.showToolbar.collectAsState(false).value,
Easy entrance exit animations.  We can even float up the definition of certain app bar elements and then animate then them individually with Modifier.enterExitAnim().

2022-04-07 14:52 UTC, BottleRocket-Colin commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/ComposeActivity.kt
> +                                navIcon = if (topLevel.value) Icons.Default.Menu else Icons.Default.ArrowBack,
Want to look at making this transition animated.

2022-04-07 14:56 UTC, BottleRocket-Colin commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/util/NavUtils.kt
> +fun NavOptionsBuilder.popToMainInclusive() {
This function could live in MainNavGraph.... @br-jared-stockton What do you think?

2022-04-08 17:11 UTC, br-jared-stockton requested changes

2022-04-08 17:11 UTC, jaredstockton commented on app/build.gradle.kts
> +    accompanistDependencies()
Woohoo!

2022-04-08 17:11 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/ComposeActivity.kt
> +class MutableStateFlowDelegate<T>(val flow: MutableStateFlow<T>) {
@BottleRocket-Colin Consider moving this to a standalone class in the `data` or `domain` module, possibly in a package similar to `com.bottlerocketstudios.brarchitecture.infrastructure.coroutine` or `com.bottlerocketstudios.brarchitecture.infrastructure.util`

2022-04-08 17:11 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/ComposeActivity.kt
> +                                        if (webViewNavigator.canGoBack) {
@BottleRocket-Colin I've been trying to think through another solution for this use case (individual screen overriding top level up nav click) but haven't come up with anything concrete as of yet.

I'm a little worried that the app could get into a state where the webViewNavigator still has some items on the backstack and the hosting screen is no longer displayed. This could possibly happen when:

1. There is some other CTA in the app bar OR on the webview screen that takes the user forwards to a new screen
2. There is some kind of deeplink triggered (through push, email, etc) that takes the user to a new screen

_Neither of these are a use case for this exact app but could easily be added to a more fully featured app :)_

It seems that pressing the up nav in those instances would continue calling `webViewNavigator.navigateBack()` until the webViewNavigator backstack is empty, effectively being a no-op (or a crash in the worst case scenario).

The potential issue revolves around the lifecycle of the webViewNavigator, which admittedly outlives the screen lifecycle here

If we can't find an alternative solution, it might be worth adding a TODO so alternatives can be explored in the future.

2022-04-08 17:11 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/MainActivityViewModel.kt
> +    val showToolbar = title.map { it.isNotEmpty() }
This is a nice addition!

2022-04-08 17:11 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/MainNavGraph.kt
> +                    controls.title = if (showToolbar) " " else ""
@BottleRocket-Colin I see why you used " " instead of "" here (toolbar visibility based on empty string or not). How about creating a constant somewhere (something like `EMPTY_TOOLBAR_TITLE`) with some kdoc mentioning why "" isn't used and to provide a little more context

2022-04-08 17:11 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/util/NavUtils.kt
> +fun NavOptionsBuilder.popToMainInclusive() {
I could go either way but I think it could make sense to move to the main nav graph, especially if there would be multiple sub nav graphs

2022-04-08 17:11 UTC, jaredstockton commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    // Accompanist
Nice to have a quick, (cmd) clickable link near the dependency:

```suggestion
    // Accompanist
    // https://github.com/google/accompanist/releases
```

2022-04-08 17:11 UTC, jaredstockton commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val ACCOMPANIST = "com.google.accompanist:accompanist-webview:0.24.5-alpha"
@BottleRocket-Colin Curious if there was anything in the alpha that you used instead of just using the latest stable version? I typically stick to stable unless there is a new feature (sometimes bugfix) provided in the alpha that provides significant functionality.

2022-04-11 16:04 UTC, BottleRocket-Colin commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val ACCOMPANIST = "com.google.accompanist:accompanist-webview:0.24.5-alpha"
I'm don't think there is a "stable" version that supports compose 1.2 yet.:
https://github.com/google/accompanist#compose-versions

2022-04-11 16:05 UTC, BottleRocket-Colin commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/ComposeActivity.kt
> +class MutableStateFlowDelegate<T>(val flow: MutableStateFlow<T>) {
moved to domain

2022-04-11 16:11 UTC, BottleRocket-Colin commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/ComposeActivity.kt
> +                                        if (webViewNavigator.canGoBack) {
Adding a comment with possible error scenarios....

2022-04-11 16:21 UTC, BottleRocket-Colin commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/MainNavGraph.kt
> +                    controls.title = if (showToolbar) " " else ""
Will do.

2022-04-11 16:34 UTC, BottleRocket-Colin commented
@br-jared-stockton - updated per your comments; let me know if I missed something

2022-04-11 17:05 UTC, br-jared-stockton commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val ACCOMPANIST = "com.google.accompanist:accompanist-webview:0.24.5-alpha"
Gotcha. This should be fine then!

2022-04-11 17:06 UTC, br-jared-stockton approved these changes
Thanks for making the changes! Looks good :)

2022-04-11 18:24 UTC, merged