Feature/ASAA-20 Commit Screen Branch Info Additions
BottleRocketStudios/Android-ArchitectureDemo pull request #83
Opened 2022-08-12 15:14 UTC by LuisRocketRangel

ASAA-20 Add Branch Info to Commit Screen 

Requirements:
-ADd Branch Info to Commit Screen UI

Solution:
-Modify API call to get branch info as well as commit info
-Add UI element to display branch name
-Add branch name list to the commit screen state

2022-08-12 15:47 UTC, BottleRocket-Colin requested changes
A couple of minor changes,

2022-08-12 15:47 UTC, BottleRocket-Colin commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryCommitViewModel.kt
> +                when (val branchCallResult = repo.getBranches(slug, repoName)) {
Look into using handlingErrors extension function here.

2022-08-12 15:47 UTC, BottleRocket-Colin commented on compose/src/main/java/com/bottlerocketstudios/compose/repository/RepositoryCommitScreen.kt
> +                    style = MaterialTheme.typography.h5.copy(fontWeight = FontWeight.Bold),
We have a toBold() extension function that performs this copy.

2022-08-12 15:47 UTC, BottleRocket-Colin commented on compose/src/main/java/com/bottlerocketstudios/compose/repository/RepositoryCommitScreen.kt
> +                    style = MaterialTheme.typography.h5.copy(fontWeight = FontWeight.Bold)
ditto w/ respect to toBold()

2022-08-12 16:26 UTC, LuisRocketRangel commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryCommitViewModel.kt
> +                when (val branchCallResult = repo.getBranches(slug, repoName)) {
Donzo!

2022-08-12 17:05 UTC, br-jared-stockton requested changes
@LuisRocketRangel Working on a review commit with some additional changes here

2022-08-12 17:05 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryCommitStateConverter.kt
> +    branchNames = branchItems.collectAsState()
@LuisRocketRangel nit: Let's add a trailing comma here to allow for simpler diffs if/when new arguments are added to `RepositoryCommitScreenState` in the future

2022-08-12 17:05 UTC, jaredstockton commented on app/src/main/java/com/bottlerocketstudios/brarchitecture/ui/repository/RepositoryCommitViewModel.kt
> +                    branchName = commit.branchName ?: ""
@LuisRocketRangel nit: Trailing comma :)

2022-08-12 17:05 UTC, br-jared-stockton commented on data/src/main/java/com/bottlerocketstudios/brarchitecture/data/model/CommitDto.kt
> +    var branchName: String?
@LuisRocketRangel We should avoid adding additional data to Dto classes, even moreso mutable data. Going to work on an alternate solution and push up a review commit later today

2022-08-15 22:06 UTC, BottleRocket-Colin approved these changes

2022-08-16 14:31 UTC, jaredstockton approved these changes

2022-08-16 17:59 UTC, merged