ASAA-39-Feature Toggles from Json File
BottleRocketStudios/Android-ArchitectureDemo pull request #94
Opened 2022-11-30 23:11 UTC by LuisRocketRangel

Requirements:
-Add Feature Toggle models
-Add ability to read Feature Toggles from Json files -Added a couple of Unit Tests
-Adding a PR now as I'm being rolled off Bench soon, please call me out as needed lol
Solution:
-Did above

2022-12-05 16:12 UTC, jaredstockton requested changes

2022-12-05 16:12 UTC, jaredstockton commented on domain/src/main/java/com/bottlerocketstudios/brarchitecture/domain/repositories/FeatureToggleRepository.kt
> +interface FeatureToggleRepository : com.bottlerocketstudios.brarchitecture.domain.models.Repository {
@LuisRocketRangel happy to sync more on the overarching approach for the feature toggles. Note that I did add some sample interfaces/classes/implementations to AASA-40 takes a different approach than shown here :)

cc: @BottleRocket-Colin

2022-12-05 16:12 UTC, jaredstockton commented on domain/src/main/java/com/bottlerocketstudios/brarchitecture/domain/models/FeatureToggle.kt
> +data class FeatureToggle(
@LuisRocketRangel Having a sealed class represent the feature toggles (as seen in AASA-40) would be ideal!

2022-12-05 16:12 UTC, jaredstockton commented on app/src/main/assets/featureToggles.json
> +[
@LuisRocketRangel You could also add the json inside a kotlin file and follow https://github.com/BottleRocketStudios/Android-ArchitectureDemo/blob/develop/docs/BEST_PRACTICES.md#language-injections even though this is a valid approach as well.

2022-12-05 16:12 UTC, jaredstockton commented on domain/src/main/java/com/bottlerocketstudios/brarchitecture/domain/models/FeatureToggle.kt
> +    val defaultValue: Boolean?,
@LuisRocketRangel This might come in a future PR but we'll definitely want to persist the feature toggles locally (likely via DataStore) so that the value persists across app restarts and is changeable via some Dev Options style UI

2022-12-05 16:12 UTC, jaredstockton commented on domain/src/main/java/com/bottlerocketstudios/brarchitecture/domain/models/FeatureToggle.kt
> +data class FeatureToggle(
That being said, in general it is preferable to use non-nullable types in domain models where able, especially for Collection types (List, Set, etc), Strings, and Booleans (unless you need the absence of a Boolean value, denoted by null)

2022-12-08 19:45 UTC, LuisRocketRangel commented on app/src/main/assets/featureToggles.json
> +[
I better follow the Best Practices, sorry about that! It's fixed!

2023-01-09 20:38 UTC, BottleRocket-Colin approved these changes

2023-01-09 20:57 UTC, merged